apiVersion: kustomize.config.k8s.io/v1/beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: leonardom/gitopsfc
  newTag: 507bb6855eb17bcbe0bb010f1fff6ae98b36f766
